---
- name: Update of group01 servers
  hosts: group01

  tasks:
    - name: Create Directory
      file:
        path: /home/centos/american2
        state: directory

- name: Update of group02 servers
  hosts: group02

  tasks:
    - name: Create Directory
      file:
        path: /home/centos/american1
        state: directory

- name: Update of group02 servers
  hosts: group02

  tasks:
    - name: Create Directory
      file:
        path: /home/centos/american2
        state: directory

- name: Install git & tree commands group01 servers
  hosts: group01

  tasks:
    - name: Install git
      become: yes
      yum:
        name: git
        state: present

- name: Update of group02 servers
  hosts: group02

  tasks:
    - name: Install git
      become: yes
      yum:
        name: git
        state: present

...

